{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-joml",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-joml-1.0-SNAPSHOT.jar",
          "url": "kmogus-joml-1.0-SNAPSHOT.jar",
          "size": 73410,
          "sha512": "19d29a8f00bfbac68a68f00f525a65a3e83947bd7d61ceedc2add12192b68449a0abb7a2f0366957bf8aaa6e5278b8a7a999881a2b3f831ffd848815e2c7fcad",
          "sha256": "afda455e22eedec4a5ff1ee2c1394ae6ce9caac3274ff185ac7f813b0f1ab37e",
          "sha1": "ce6ca24b55762c471fc37c8c7a3ee0efc1f3d32d",
          "md5": "acbd30a12d5d6b54bf9a4a09fa2ab5f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "kmogus-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-joml-1.0-SNAPSHOT.jar",
          "url": "kmogus-joml-1.0-SNAPSHOT.jar",
          "size": 73410,
          "sha512": "19d29a8f00bfbac68a68f00f525a65a3e83947bd7d61ceedc2add12192b68449a0abb7a2f0366957bf8aaa6e5278b8a7a999881a2b3f831ffd848815e2c7fcad",
          "sha256": "afda455e22eedec4a5ff1ee2c1394ae6ce9caac3274ff185ac7f813b0f1ab37e",
          "sha1": "ce6ca24b55762c471fc37c8c7a3ee0efc1f3d32d",
          "md5": "acbd30a12d5d6b54bf9a4a09fa2ab5f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-joml-1.0-SNAPSHOT-sources.jar",
          "url": "kmogus-joml-1.0-SNAPSHOT-sources.jar",
          "size": 5805,
          "sha512": "c21023baa5e1f9fd031c2dacae9e499724ae67e5aa294f28f617c2b5f6b7b44b48d28d656fde2099c94937d7c0d978adfb739b41bd0d5d59d637171d392d4565",
          "sha256": "2f7e963890e9b5689d9c2b9e83fbada3f03e4d416aa68fa5df433d8128bc0890",
          "sha1": "76961a3debadccaf0d226a042061b59fb3dfa9f2",
          "md5": "37b22a2d8310eaf76ff6f71593f99577"
        }
      ]
    }
  ]
}
