{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "cfr",
    "version": "0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cfr-0.2-SNAPSHOT.jar",
          "url": "cfr-0.2-SNAPSHOT.jar",
          "size": 2058257,
          "sha512": "c3e12f305a16c9b8c6afa5ea9803ab6c277b613329ba8c5d34739a67c5a86e41444c516ce5e089af35a3c1c4e1aeae784f58d915a86d7a113a2dadcd4b6a5f97",
          "sha256": "b6b5dd5c399b32b0d54b7a43f8797de4ac16a8a9c59b2c23a35b1e8dc5abdfe9",
          "sha1": "4cc17f25cdde17e2cbc08af77300057aeea0ad32",
          "md5": "996c7a26dc18c64088a8e1a0ab5c1c13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "cfr-0.2-SNAPSHOT.jar",
          "url": "cfr-0.2-SNAPSHOT.jar",
          "size": 2058257,
          "sha512": "c3e12f305a16c9b8c6afa5ea9803ab6c277b613329ba8c5d34739a67c5a86e41444c516ce5e089af35a3c1c4e1aeae784f58d915a86d7a113a2dadcd4b6a5f97",
          "sha256": "b6b5dd5c399b32b0d54b7a43f8797de4ac16a8a9c59b2c23a35b1e8dc5abdfe9",
          "sha1": "4cc17f25cdde17e2cbc08af77300057aeea0ad32",
          "md5": "996c7a26dc18c64088a8e1a0ab5c1c13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cfr-0.2-SNAPSHOT-sources.jar",
          "url": "cfr-0.2-SNAPSHOT-sources.jar",
          "size": 1014540,
          "sha512": "303d18d9aa2c198907420b17a7ba48e16d8ee7a31c650d782db0b611635c0606377c245cc0c3e0cda0b2d7fc3ed2475b0c157e5c4f7d5f7b1e7c30ee2ac0510c",
          "sha256": "2d2206cf7c8d3569274fe89f32b685ebd2218896cfe897c4efffea6090dfc06c",
          "sha1": "05f3e507b9a2831827ade86fd045c5ab2730c648",
          "md5": "8d670d3c71dcd7299259c87850910093"
        }
      ]
    }
  ]
}
