{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-struct-codegen",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-1.1-SNAPSHOT.jar",
          "url": "kmogus-struct-codegen-1.1-SNAPSHOT.jar",
          "size": 4815,
          "sha512": "3cd16e2e5c64235a4fa10dd5300eb09e899a4a7603ca871320a6d9a4498d14f2156b614f671208794992daf1362c832af53886f8bbf1ac759dbabef455134550",
          "sha256": "6613ec08d001d1b248c54827e5f75e42f3b9b5441b52664614b9c475587e9821",
          "sha1": "c2059a2a94302682f283fb34e9a7782b09269164",
          "md5": "d1778e8fe0a083a9ea0bc5fcffa201ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-struct-api",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "ktgen",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-1.1-SNAPSHOT.jar",
          "url": "kmogus-struct-codegen-1.1-SNAPSHOT.jar",
          "size": 4815,
          "sha512": "3cd16e2e5c64235a4fa10dd5300eb09e899a4a7603ca871320a6d9a4498d14f2156b614f671208794992daf1362c832af53886f8bbf1ac759dbabef455134550",
          "sha256": "6613ec08d001d1b248c54827e5f75e42f3b9b5441b52664614b9c475587e9821",
          "sha1": "c2059a2a94302682f283fb34e9a7782b09269164",
          "md5": "d1778e8fe0a083a9ea0bc5fcffa201ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-struct-codegen-1.1-SNAPSHOT-sources.jar",
          "url": "kmogus-struct-codegen-1.1-SNAPSHOT-sources.jar",
          "size": 1588,
          "sha512": "fe3b6e1c9e71592db0215102568699d3b98556e8fedcab559a9eb84c0e877351ea6227a0db61c5e115abd13028769d0fb13be285f3fba36c99f9734c887aca3c",
          "sha256": "85a713d2bc022225a7256a674dc653176e92743ab152952fb001bd02f594b788",
          "sha1": "b58789ea47cb771d88c2a161e958ad59f3d5cbc7",
          "md5": "e5673eca66af58b6505c89525f1438b4"
        }
      ]
    }
  ]
}
