{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "fastmc-common",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElementsJava8",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.1-SNAPSHOT-java8.jar",
          "url": "fastmc-common-1.1-SNAPSHOT-java8.jar",
          "size": 146260,
          "sha512": "a3b10b40317a2d20c67322079ddfe1c1c075c09bae0d48c25ff1c653b9df8a114e06fb51ac89454f334cd992d64206e9c117140b294e0dca32767b125062ca15",
          "sha256": "ee9b112ddf8084dec6ea47ac8883b95cb9e45dc464a81febcaca381788e3e286",
          "sha1": "c5e72e192e6a1dfd9ec2bf8b3792409cfc947411",
          "md5": "9195aa60d0672185e7ab7bba216d232f"
        }
      ]
    },
    {
      "name": "runtimeElementsJava8",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.1-SNAPSHOT-java8.jar",
          "url": "fastmc-common-1.1-SNAPSHOT-java8.jar",
          "size": 146260,
          "sha512": "a3b10b40317a2d20c67322079ddfe1c1c075c09bae0d48c25ff1c653b9df8a114e06fb51ac89454f334cd992d64206e9c117140b294e0dca32767b125062ca15",
          "sha256": "ee9b112ddf8084dec6ea47ac8883b95cb9e45dc464a81febcaca381788e3e286",
          "sha1": "c5e72e192e6a1dfd9ec2bf8b3792409cfc947411",
          "md5": "9195aa60d0672185e7ab7bba216d232f"
        }
      ]
    },
    {
      "name": "apiElementsJava17",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.1-SNAPSHOT-java17.jar",
          "url": "fastmc-common-1.1-SNAPSHOT-java17.jar",
          "size": 146808,
          "sha512": "8bb9209610e213b661fba2f3ea33faac80daeb3dfb61e8b5eccd1489dbfcd4250f94fa3e3600a95ee751aa04853e52388498628f5251a598a28241988d82a59e",
          "sha256": "fa47dd0ba2f5fe97c21240cfbe67516bdfb2bfb5b0562afda54ee58c0c364a8d",
          "sha1": "0d18a45558a0110b20c820d81a7adbc3485f5ff3",
          "md5": "fb4ea78dd87f612849c180769ec9f300"
        }
      ]
    },
    {
      "name": "runtimeElementsJava17",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.1-SNAPSHOT-java17.jar",
          "url": "fastmc-common-1.1-SNAPSHOT-java17.jar",
          "size": 146808,
          "sha512": "8bb9209610e213b661fba2f3ea33faac80daeb3dfb61e8b5eccd1489dbfcd4250f94fa3e3600a95ee751aa04853e52388498628f5251a598a28241988d82a59e",
          "sha256": "fa47dd0ba2f5fe97c21240cfbe67516bdfb2bfb5b0562afda54ee58c0c364a8d",
          "sha1": "0d18a45558a0110b20c820d81a7adbc3485f5ff3",
          "md5": "fb4ea78dd87f612849c180769ec9f300"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastmc-common-1.1-SNAPSHOT-sources.jar",
          "url": "fastmc-common-1.1-SNAPSHOT-sources.jar",
          "size": 48368,
          "sha512": "6b5430bd71d1d8e470df6d0c8f7d344bdcd1344412611b64c97d6c6b2833cd9966008916552126565e59c29a96437adb8c79a95f1d6ed963fdc3620cb9848de7",
          "sha256": "f4259cb0c602134bf068d968de7d023026aabd37e753cb96a424cfaf6f95a7db",
          "sha1": "821b342966c33e063a576a5417a70556d088459b",
          "md5": "db7177d70d649ae2ce18b995e16ca985"
        }
      ]
    }
  ]
}
