{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-struct-codegen",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-1.1.0.jar",
          "url": "kmogus-struct-codegen-1.1.0.jar",
          "size": 4818,
          "sha512": "928fc332d6555498a22912e02a1fc9872a6e16c587fb2ec5ca8d878d2e4ebb9e218967bbc83146132262c9efe8e86ae80951349fbab5c9217cb0b1b305d72c75",
          "sha256": "f5077e54fa13c62690563dce7e18331f1e276342799d613ad685b08c82fd5de1",
          "sha1": "ef5e174a86e52eba55984def714424b91a3e9fbe",
          "md5": "948843a74e312f80cd517128d81d2564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-struct-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "ktgen",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-1.1.0.jar",
          "url": "kmogus-struct-codegen-1.1.0.jar",
          "size": 4818,
          "sha512": "928fc332d6555498a22912e02a1fc9872a6e16c587fb2ec5ca8d878d2e4ebb9e218967bbc83146132262c9efe8e86ae80951349fbab5c9217cb0b1b305d72c75",
          "sha256": "f5077e54fa13c62690563dce7e18331f1e276342799d613ad685b08c82fd5de1",
          "sha1": "ef5e174a86e52eba55984def714424b91a3e9fbe",
          "md5": "948843a74e312f80cd517128d81d2564"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-struct-codegen-1.1.0-sources.jar",
          "url": "kmogus-struct-codegen-1.1.0-sources.jar",
          "size": 1588,
          "sha512": "08f8098488be673f85102b05d0a895e79693a59f7defe0aeea62f7e83cf1c7717d14917d7e43b42b79166c3bdd112420ab00757bd45d5651e23efeffbe925ed6",
          "sha256": "b27e1d8abe64a9dfeaa1a5e4922e713ae45c52ec944ae4d81770c89c0452b829",
          "sha1": "f6898529432fe3cfa6f1dfbccd19c673dc139bfd",
          "md5": "3e0820ffbee61f980481c20152c85cfb"
        }
      ]
    }
  ]
}
