{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-struct-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-plugin-1.0.0.jar",
          "url": "kmogus-struct-plugin-1.0.0.jar",
          "size": 31391,
          "sha512": "eac1a2e3f51e801a9020d3dd81cd041184e9ea04a849d6ba9941f7e14ff38bf1f2ba8f44432ed1fcef1aa0d42a46bbe4070276ef3806dc46a7fe59f3f0771918",
          "sha256": "1a081225a278516493e9d1ba6f4a944f41d8aa51cc7dc177c8794f75cb1638ab",
          "sha1": "1258e56386e600e3d176baa1317ffa5fa625882a",
          "md5": "5bdd6ddccb83dfe39241af800f175692"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.20-1.0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "kmogus-struct-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-plugin-1.0.0.jar",
          "url": "kmogus-struct-plugin-1.0.0.jar",
          "size": 31391,
          "sha512": "eac1a2e3f51e801a9020d3dd81cd041184e9ea04a849d6ba9941f7e14ff38bf1f2ba8f44432ed1fcef1aa0d42a46bbe4070276ef3806dc46a7fe59f3f0771918",
          "sha256": "1a081225a278516493e9d1ba6f4a944f41d8aa51cc7dc177c8794f75cb1638ab",
          "sha1": "1258e56386e600e3d176baa1317ffa5fa625882a",
          "md5": "5bdd6ddccb83dfe39241af800f175692"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-struct-plugin-1.0.0-sources.jar",
          "url": "kmogus-struct-plugin-1.0.0-sources.jar",
          "size": 5598,
          "sha512": "13cdbf49570298221ecc7d4442c63f7b3f588479e6bd5f7af20f8f419a73221cf218b0a184adc1a452ed656c6404279eb67bb839bb82b3c37e4b53c4ea1217fa",
          "sha256": "2288f31257553d9b4d359a1a380bc2998a480c6e563539d7a78439340b06a2e1",
          "sha1": "18c515d999075c356508f7c281f2eaad4a8e5acc",
          "md5": "3ae47b2b18e7a8c3558fbd710c1b75d0"
        }
      ]
    }
  ]
}
