{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-loader-plugin",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.1.0.jar",
          "url": "mod-loader-plugin-1.1.0.jar",
          "size": 239399,
          "sha512": "4257ff753b42d5b3ffbc65cc892af4a1661d6763f7384700331bdf54dd05c243915a793288c792492727f51142f37651be47555d0f23a8fa1297def76bf1459d",
          "sha256": "3bacb8b4d6e70b189109641092ae88f315c9b5dda60a6f2272caa8567c7ebd72",
          "sha1": "3c45e1576902937590ae3350ae6160a339c721c9",
          "md5": "14b90530de8175034502044aac20e29f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.22"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "mod-loader-plugin-1.1.0.jar",
          "url": "mod-loader-plugin-1.1.0.jar",
          "size": 239399,
          "sha512": "4257ff753b42d5b3ffbc65cc892af4a1661d6763f7384700331bdf54dd05c243915a793288c792492727f51142f37651be47555d0f23a8fa1297def76bf1459d",
          "sha256": "3bacb8b4d6e70b189109641092ae88f315c9b5dda60a6f2272caa8567c7ebd72",
          "sha1": "3c45e1576902937590ae3350ae6160a339c721c9",
          "md5": "14b90530de8175034502044aac20e29f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.1.0-sources.jar",
          "url": "mod-loader-plugin-1.1.0-sources.jar",
          "size": 150268,
          "sha512": "f230bc0bb9f01d3c19d8afd93c0cfc2eb0241b5f9944a4ca85ad99a2949cc3da3336db78506dd1d33aded2e9c61c87fbd6981312c6b6012fabd92ced82e85898",
          "sha256": "909e9c504fe768f56c54a60e18b01652d304173362b29f0cedef5eead1cba31a",
          "sha1": "e2cddf8be6247840c78bb572da220d014d37adb9",
          "md5": "93ccbcb1c6c5de400963239880e2d576"
        }
      ]
    }
  ]
}
