{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-struct-codegen-runtime",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-runtime-1.1.0.jar",
          "url": "kmogus-struct-codegen-runtime-1.1.0.jar",
          "size": 27579,
          "sha512": "7e50e64bc985c3e8bbc3260e4d83f59e07a312a1f7261fe85c0553a066e4ce199c4cb96767707de099db28978d453d7cd31acb93e497d375ed46f31cd6d1b2d5",
          "sha256": "a8a105e0465936f5506b48b85495aca8f8f85a1721b0752651b6fd5f1db32d29",
          "sha1": "025e08c737534418cbb2902966484aeda36f04c3",
          "md5": "dc5baa74baa0383b39bb578126699584"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-struct-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "ktgen-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-runtime-1.1.0.jar",
          "url": "kmogus-struct-codegen-runtime-1.1.0.jar",
          "size": 27579,
          "sha512": "7e50e64bc985c3e8bbc3260e4d83f59e07a312a1f7261fe85c0553a066e4ce199c4cb96767707de099db28978d453d7cd31acb93e497d375ed46f31cd6d1b2d5",
          "sha256": "a8a105e0465936f5506b48b85495aca8f8f85a1721b0752651b6fd5f1db32d29",
          "sha1": "025e08c737534418cbb2902966484aeda36f04c3",
          "md5": "dc5baa74baa0383b39bb578126699584"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-struct-codegen-runtime-1.1.0-sources.jar",
          "url": "kmogus-struct-codegen-runtime-1.1.0-sources.jar",
          "size": 4350,
          "sha512": "496ad4851d6de561eb2c80fab61d4dde7148c44b25b324a773167e067bd5f406bf9764b66a0e07f332493ecb996cb294391a84a615d74db1260ac2dc5237d05d",
          "sha256": "add8e05e3846171acd477094bb2a692e960935832b1dcbec88ac2c8be1685555",
          "sha1": "52d2fc3d2862065dd5a676b1231f81bd3a0eabbb",
          "md5": "0e15da7dce1b3f7de43e622b12ed516f"
        }
      ]
    }
  ]
}
