{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-struct-api",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-api-1.1.0.jar",
          "url": "kmogus-struct-api-1.1.0.jar",
          "size": 2868,
          "sha512": "20d177a7c512e67a7c8b2c3e2ca85502918c10fb85996a0d0b0f8b855ff2be21247f573f18401963782e33aa94c19e6917cba267a3a81c6ab7cb390113d112a4",
          "sha256": "2c82423933ae4ac46ed1040be14aeae926e74a9484d18228eb7e9e83e144ffad",
          "sha1": "e0e5562bc61fa80bb6ac2a665cb0f0c6628863e3",
          "md5": "6529332421c355fb03f23dccb0bcb683"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-api-1.1.0.jar",
          "url": "kmogus-struct-api-1.1.0.jar",
          "size": 2868,
          "sha512": "20d177a7c512e67a7c8b2c3e2ca85502918c10fb85996a0d0b0f8b855ff2be21247f573f18401963782e33aa94c19e6917cba267a3a81c6ab7cb390113d112a4",
          "sha256": "2c82423933ae4ac46ed1040be14aeae926e74a9484d18228eb7e9e83e144ffad",
          "sha1": "e0e5562bc61fa80bb6ac2a665cb0f0c6628863e3",
          "md5": "6529332421c355fb03f23dccb0bcb683"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-struct-api-1.1.0-sources.jar",
          "url": "kmogus-struct-api-1.1.0-sources.jar",
          "size": 1041,
          "sha512": "742804bd95eb66de50a8c197c33495ed54448b40498eacac74330593ed657bff8a346d12bd41c18ac77cc6090c11e4fa1b98227db719d9066f7be7360c984106",
          "sha256": "930988c6f2b6e388e3d289350a9e33b316ea07d5f12c30d3dfbdc193b8ecf9c8",
          "sha1": "b2e88f3fe7362356e54d8d0382c7710fecd613c7",
          "md5": "4f6af514a2b5d63493afbd15a59f1b85"
        }
      ]
    }
  ]
}
