{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-setup",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-setup-1.3.2.jar",
          "url": "mod-setup-1.3.2.jar",
          "size": 79991,
          "sha512": "bbe3844acd479320feebaa4598ade2b6ca1be8da5b1fb4046f2f4b5aeb5d1732550f46298905770770eb69347a80b7bdd4aae0f0cecf0612aa8f1ef4f96be93f",
          "sha256": "b4f333b3fb4e5975f30359d8c0080c8c9cfaaa371e588636ce18065a7aedbe46",
          "sha1": "ee04fa8cd495b071f4211766609871b5591077a6",
          "md5": "b7dd195633029fea431c28ad4d94fd12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "jar-optimizer",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "fast-remapper",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "mod-loader-plugin",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.7-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "requires": "6.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mod-setup-1.3.2.jar",
          "url": "mod-setup-1.3.2.jar",
          "size": 79991,
          "sha512": "bbe3844acd479320feebaa4598ade2b6ca1be8da5b1fb4046f2f4b5aeb5d1732550f46298905770770eb69347a80b7bdd4aae0f0cecf0612aa8f1ef4f96be93f",
          "sha256": "b4f333b3fb4e5975f30359d8c0080c8c9cfaaa371e588636ce18065a7aedbe46",
          "sha1": "ee04fa8cd495b071f4211766609871b5591077a6",
          "md5": "b7dd195633029fea431c28ad4d94fd12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-setup-1.3.2-sources.jar",
          "url": "mod-setup-1.3.2-sources.jar",
          "size": 16040,
          "sha512": "dfc887182ed4a5d789b3e45df8d8157f39dc3064bf54eec8839af58c112e3f5cf51f145ac891f4967440757ee82494d6ccbe66fb053bbd72d084ff986fd3a6e7",
          "sha256": "ebf6ee305f4dc3e5bd4af62495ae81bfe001cdce4c45ec4fe9601bc4555db567",
          "sha1": "212c5ca6e55bd5d4d081f1652e6b4716404af1dc",
          "md5": "078a1d5bb02f94c55f38c9d367b6fece"
        }
      ]
    }
  ]
}
