{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-setup",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-setup-1.3.1.jar",
          "url": "mod-setup-1.3.1.jar",
          "size": 77760,
          "sha512": "1835072c36d1a4165a5631552c23802ca01f56f40ed0603dbb99c30e862ac17c4cee8f8206da9474407136b0e570cdbecdde1a374964f4d782c9ce9823c93f17",
          "sha256": "8999dbc7a177deccb118ffc011eaaa6cf90d1aa89a31f6e8e71c398606409d94",
          "sha1": "1b84942db5286df556efab07340e5bed27eedd4b",
          "md5": "1e1761bc4cba9022b45f46bb3d014a16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "jar-optimizer",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "fast-remapper",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "mod-loader-plugin",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "requires": "6.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mod-setup-1.3.1.jar",
          "url": "mod-setup-1.3.1.jar",
          "size": 77760,
          "sha512": "1835072c36d1a4165a5631552c23802ca01f56f40ed0603dbb99c30e862ac17c4cee8f8206da9474407136b0e570cdbecdde1a374964f4d782c9ce9823c93f17",
          "sha256": "8999dbc7a177deccb118ffc011eaaa6cf90d1aa89a31f6e8e71c398606409d94",
          "sha1": "1b84942db5286df556efab07340e5bed27eedd4b",
          "md5": "1e1761bc4cba9022b45f46bb3d014a16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-setup-1.3.1-sources.jar",
          "url": "mod-setup-1.3.1-sources.jar",
          "size": 15996,
          "sha512": "fd91adb53eaebffa44a928dd34f34834eb872f30657ff70d504807a138bde187d889ddfa137097bfc06fe1a17525cac92a23b98f1b1be927d96b465e26299f27",
          "sha256": "2fef6c6a84beb369dd8e96f32173139cef4b22db598e9edf528238030f471759",
          "sha1": "c835a84644501cfc8ffab74e515102848ae14c19",
          "md5": "1fb5b6f8c33a66466628660f3f26e1e6"
        }
      ]
    }
  ]
}
