{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "jar-optimizer",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-optimizer-1.2.0.jar",
          "url": "jar-optimizer-1.2.0.jar",
          "size": 60549,
          "sha512": "2fd0116791b1ab9b7f319d2b842e336820e0aea89994754aa8c713231128c3ea54db29c760863b756b508ba1bd27a7a60b386670394db56614f7317e38a9ab6c",
          "sha256": "dbbc17f358eeea09f7c3f380e99d179bb5f95d7435fefcf8143e386b335acfe8",
          "sha1": "5f9df122864d1d90b0d70e620923879ad2ea9a74",
          "md5": "1dc09f56521e263fb497bd97fd07a88b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "jar-optimizer-1.2.0.jar",
          "url": "jar-optimizer-1.2.0.jar",
          "size": 60549,
          "sha512": "2fd0116791b1ab9b7f319d2b842e336820e0aea89994754aa8c713231128c3ea54db29c760863b756b508ba1bd27a7a60b386670394db56614f7317e38a9ab6c",
          "sha256": "dbbc17f358eeea09f7c3f380e99d179bb5f95d7435fefcf8143e386b335acfe8",
          "sha1": "5f9df122864d1d90b0d70e620923879ad2ea9a74",
          "md5": "1dc09f56521e263fb497bd97fd07a88b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-optimizer-1.2.0-sources.jar",
          "url": "jar-optimizer-1.2.0-sources.jar",
          "size": 4480,
          "sha512": "ca3a4ae25c0b3dc43ed4aeca683a79a17fedc940b93a6703e194a9e20fe214b9e7c6a6ab0e04271bad4cc1fec5c3345183d49daf129f64f9f42ef170d87d3f1e",
          "sha256": "5be1d0ecfbc7a1823fc506cbcb71e1655a0ef2821e3d983800a5a5dc1ebbb1f7",
          "sha1": "79f5cd19c2a13f4cca7e5a6b31198ca219fd98ac",
          "md5": "3c5794d754197b16bece6c1961a3f407"
        }
      ]
    }
  ]
}
