{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "kmogus-struct-codegen-runtime",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-runtime-1.1-SNAPSHOT.jar",
          "url": "kmogus-struct-codegen-runtime-1.1-SNAPSHOT.jar",
          "size": 27328,
          "sha512": "351e09a9dd09b43c21200ccb40d16a7563d716e01a766fc4cb14185913f60d2aaf0ed4392b02fc8694da6a1333e745875177800733e4adce34a278f2452593c4",
          "sha256": "6dd1185c621f6574dd938d333ed6ba1bc85ddefe0a6cce91004822738f11ae16",
          "sha1": "6abad02bbe0716c25211e2cfab321fdc17042744",
          "md5": "0df87d447871838a631d04a8de8b0b5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.luna5ama",
          "module": "kmogus-struct-api",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "ktgen-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmogus-struct-codegen-runtime-1.1-SNAPSHOT.jar",
          "url": "kmogus-struct-codegen-runtime-1.1-SNAPSHOT.jar",
          "size": 27328,
          "sha512": "351e09a9dd09b43c21200ccb40d16a7563d716e01a766fc4cb14185913f60d2aaf0ed4392b02fc8694da6a1333e745875177800733e4adce34a278f2452593c4",
          "sha256": "6dd1185c621f6574dd938d333ed6ba1bc85ddefe0a6cce91004822738f11ae16",
          "sha1": "6abad02bbe0716c25211e2cfab321fdc17042744",
          "md5": "0df87d447871838a631d04a8de8b0b5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmogus-struct-codegen-runtime-1.1-SNAPSHOT-sources.jar",
          "url": "kmogus-struct-codegen-runtime-1.1-SNAPSHOT-sources.jar",
          "size": 4367,
          "sha512": "37919f42b25c484b0b84bc8c767a3f3d2a1bd664edbbd90a0b3458f0a9f2bebc97c9509271da25286928c19825676a922822baade6c7da2e7c6ec05cdd1a234f",
          "sha256": "1713252b8b0326166eb1ada00d7627dd4d2321b1eca6af8d799e432c30bb055a",
          "sha1": "4401d2f4cace65c0d1ef8785d0bf85b433fb720b",
          "md5": "0332e4bfedef6694c57bf1e93d0a6ec0"
        }
      ]
    }
  ]
}
