{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-setup",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-setup-1.3-SNAPSHOT.jar",
          "url": "mod-setup-1.3-SNAPSHOT.jar",
          "size": 78011,
          "sha512": "3cbba8886ab95f8aab5d97dc85a0efa4864f5a699ca23c0a6cfc81a1f3c00039a1ccf8515dde7567c2e5a30c3011b2b34038dc9ac9b326895dc6c96b094b8d50",
          "sha256": "0c4ff9eacc4827fb0f46a13facadfdadeb346fab015bab835f4ab9f8d79f3243",
          "sha1": "1330499bd137b951185e56cf450474d1124f1a27",
          "md5": "c58e2e9681cec2f16fdd6be7e019cf05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "jar-optimizer",
          "version": {
            "requires": "1.2-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "fast-remapper",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "mod-loader-plugin",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "requires": "6.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "mod-setup-1.3-SNAPSHOT.jar",
          "url": "mod-setup-1.3-SNAPSHOT.jar",
          "size": 78011,
          "sha512": "3cbba8886ab95f8aab5d97dc85a0efa4864f5a699ca23c0a6cfc81a1f3c00039a1ccf8515dde7567c2e5a30c3011b2b34038dc9ac9b326895dc6c96b094b8d50",
          "sha256": "0c4ff9eacc4827fb0f46a13facadfdadeb346fab015bab835f4ab9f8d79f3243",
          "sha1": "1330499bd137b951185e56cf450474d1124f1a27",
          "md5": "c58e2e9681cec2f16fdd6be7e019cf05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-setup-1.3-SNAPSHOT-sources.jar",
          "url": "mod-setup-1.3-SNAPSHOT-sources.jar",
          "size": 15984,
          "sha512": "fa19b18d9232c6b778a5f0669debe25d1b3c1b8c5381dd500ad57087857ac5f466c9a1238c18e0e9438d537b8d382d81c45c4e66c56b76927f004885ec2d3d6c",
          "sha256": "f59c96c21cb72adafc0326896300d3a567004020f201e6f3e6d07d46e78523eb",
          "sha1": "5741f500a2c9308579459f314651c5a6c698d4fb",
          "md5": "a8824973740d1e20d38a0c995e2082d4"
        }
      ]
    }
  ]
}
